name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v5

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache downloaded dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: bun-install-cache-${{ runner.os }}-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            bun-install-cache-${{ runner.os }}-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint code
        run: bun run lint
